CREATE TABLE IF NOT EXISTS FORNECEDORES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RAZAOSOCIALFORNECEDOR VARCHAR(255),
    CNPJFORNECEDOR VARCHAR(30),
    ENDERECO VARCHAR(255),
    BAIRRO VARCHAR(100),
    MUNICIPIO VARCHAR(100),
    CEP VARCHAR(20)
);